# .pre-commit-config.yaml

# Optional: Set a minimum pre-commit version
# min_pre_commit_version: '2.9.0'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    # -   id: check-added-large-files # Optional: good for catching accidental large file commits

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0 # Use the latest stable version of flake8
    hooks:
    -   id: flake8
        # Optional: specify arguments for flake8
        # args: ['--max-line-length=88', '--extend-ignore=E203']
        # It's often better to configure flake8 via .flake8, setup.cfg, or pyproject.toml
        # so it's consistent whether run via pre-commit or manually.
        additional_dependencies: [
            # Add any flake8 plugins you use here, e.g.:
            # 'flake8-bugbear',
            # 'flake8-comprehensions',
            # 'flake8-docstrings',
            # 'pep8-naming'
        ]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6 # Use the latest stable version
    hooks:
    -   id: codespell
        args: [
            "--ignore-words-list=SER,xxxx",
            # Or point to a file:
            #"--ignore-words=.codespellignore",
            "--skip=*.md,*.json,*.lock,*.svg,*.css,*.html", # Skip file types less likely to need it
            # "--check-filenames",
            # "--check-hidden"
        ]
        # You can create a .codespellignore file with one word per line for words to ignore.
